# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
controller_manager_ns: controller_manager
controller_list:
  - name: dual_arm
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints: 
      - joint_2
      - joint_3
      - joint_4 
      - joint_5
      - joint_6 
      - joint_7 
      - joint_2_m
      - joint_3_m 
      - joint_4_m 
      - joint_5_m 
      - joint_6_m 
      - joint_7_m
      - gripper_joint_m
      - gripper_base_joint_m
      - gripper_tcp_joint_m
  - name: mp
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_2
      - joint_3
      - joint_4 
      - joint_5
      - joint_6 
      - joint_7 
  - name: mp_m
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_2_m
      - joint_3_m 
      - joint_4_m 
      - joint_5_m 
      - joint_6_m 
      - joint_7_m
      - gripper_joint_m
      - gripper_base_joint_m
      - gripper_tcp_joint_m