# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
controller_manager_ns: controller_manager
controller_list:
  - name: mp_m
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_2_m
      - joint_3_m 
      - joint_4_m 
      - joint_5_m 
      - joint_6_m 
      - joint_7_m 

      # - joint_2
      # - joint_2_m
      # - joint_3
      # - joint_3_m 
      # - joint_4
      # - joint_4_m  
      # - joint_5
      # - joint_5_m
      # - joint_6
      # - joint_6_m 
      # - joint_7 
      # - joint_7_m
  # - name: mp_cont
  # - name: mp_controller
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   default: true
  #   joints: 
  #     - joint_2
  #     - joint_3
  #     - joint_4 
  #     - joint_5
  #     - joint_6 
  #     - joint_7 
  # - name: mp_m_controller
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   default: true
  #   joints: 
  #     - joint_2_m
  #     - joint_3_m
  #     - joint_4_m
  #     - joint_5_m
  #     - joint_6_m 
  #     - joint_7_m 

  # - name: dual_arm_controller
  #   action_ns: joint_trajectory_action
  #   type: FollowJointTrajectory
  #   default: true
  #   joints: 
  #     - joint_2
  #     - joint_3
  #     - joint_4 
  #     - joint_5
  #     - joint_6 
  #     - joint_7 
  #     - joint_2_m
  #     - joint_3_m 
  #     - joint_4_m 
  #     - joint_5_m 
  #     - joint_6_m 
  #     - joint_7_m

  # ['joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6', 'joint_7']

  # ['joint_2_m', 'joint_3_m', 'joint_4_m', 'joint_5_m', 'joint_6_m', 'joint_7_m']