controller_list:
  - name: fake_mp_controller
    joints:
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7 
  - name: fake_mp_m_controller
    joints:
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m
      - joint_7_m
  - name: fake_dual_arm_controller
    joints:
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m
      - joint_7_m