joint_limits_m:
  joint_2_m:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_3_m:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_4_m:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_5_m:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_6_m:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 1.46608
  joint_7_m:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 1.46608